#!/bin/bash

#do this if you want to clone from the repo
git clone https://github.com/tisaac/p4est -b feature-connrefine p4est_feature
cd p4est_feature
git submodule init
git submodule update
./bootstrap
git branch
tar --exclude='./.git' --exclude='./sc/.git' -cjf ../p4est_feature.tar.bj *
cd ..
rm -rf p4est_feature
