name: hnumo CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Fortran compiler
      run: sudo apt-get install -y gfortran

    - name: Set up Open MPI
      run: sudo apt-get install -y openmpi-bin libopenmpi-dev

    - name: Compile Fortran code
      run: make hnumo

    - name: Print home directory
      run: echo $HOME

    - name: Run MPI tests
      run: mpirun -np 1 $HOME/work/h-NUMO/h-NUMO/bin/numo3d
